
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Sarita
 */
public class ComprobacionNumerica extends javax.swing.JFrame {

    /**
     * Creates new form ComprobacionNumerica
     */
    public ComprobacionNumerica() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblNum = new javax.swing.JLabel();
        lblMensaje = new javax.swing.JLabel();
        txtNumero = new javax.swing.JTextField();
        btnComprobar = new javax.swing.JButton();
        btnPrimo = new javax.swing.JButton();
        btnPrimo2 = new javax.swing.JButton();
        btnEN1 = new javax.swing.JButton();
        btnRaiz = new javax.swing.JButton();
        lblMen = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("COMPROBACION NUMERICA");

        lblNum.setText("NUMERO:");

        lblMensaje.setText("Respuesta");

        btnComprobar.setText("PERFECTO");
        btnComprobar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComprobarActionPerformed(evt);
            }
        });

        btnPrimo.setText("PRIMO");
        btnPrimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrimoActionPerformed(evt);
            }
        });

        btnPrimo2.setText("PRIMO<7");
        btnPrimo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrimo2ActionPerformed(evt);
            }
        });

        btnEN1.setText("ENTERO_PRIMO<");
        btnEN1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEN1ActionPerformed(evt);
            }
        });

        btnRaiz.setText("RAIZ");
        btnRaiz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRaizActionPerformed(evt);
            }
        });

        lblMen.setText("..........");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(118, 118, 118))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblMensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 444, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(19, 19, 19)
                            .addComponent(btnComprobar)
                            .addGap(18, 18, 18)
                            .addComponent(btnPrimo)
                            .addGap(18, 18, 18)
                            .addComponent(btnPrimo2)
                            .addGap(18, 18, 18)
                            .addComponent(btnEN1)
                            .addGap(18, 18, 18)
                            .addComponent(btnRaiz))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(lblMen, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(64, 64, 64)
                                .addComponent(lblNum)
                                .addGap(60, 60, 60)
                                .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(47, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel1)
                .addGap(75, 75, 75)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNum)
                    .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblMen)
                .addGap(9, 9, 9)
                .addComponent(lblMensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnComprobar)
                    .addComponent(btnPrimo)
                    .addComponent(btnPrimo2)
                    .addComponent(btnEN1)
                    .addComponent(btnRaiz))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnComprobarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComprobarActionPerformed
        // TODO add your handling code here:
        int numero = Integer.parseInt(txtNumero.getText());
        int resul = 0;
        for (int i = 1; i < numero; i++) {
            if (numero % i == 0) {
        // Si numero es divisible por i, acumula la suma
        resul += i;
}   
          if(resul == numero){
              lblMensaje.setText("El numero es perfecto");
        } else{ 
            lblMensaje.setText("El numero no es perfecto");
          }
        }
        
        
        
        
        
    }//GEN-LAST:event_btnComprobarActionPerformed

    private void btnPrimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrimoActionPerformed
        // TODO add your handling code here:
       int num = Integer.parseInt(txtNumero.getText());
       
    boolean prime = true; 
    for(int i = 2; i < num; i++) {
        if (num % i == 0) {
            prime = false;
            break;
        }
    }
    if (prime)
        lblMensaje.setText("EL NUMERO ES PRIMO.");
    else
        lblMensaje.setText("EL NUMERO NO ES PRIMO.");

    }//GEN-LAST:event_btnPrimoActionPerformed

    private void btnPrimo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrimo2ActionPerformed
        // TODO add your handling code here:
       int num = Integer.parseInt(txtNumero.getText());
       if(num<7){
    boolean prime = true; 
    for(int i = 2; i < num; i++) {
        if (num % i == 0) {
            prime = false;
            break;
        }
    }
    if (prime)
        lblMensaje.setText("EL NUMERO ES PRIMO.");
    else
        lblMensaje.setText("EL NUMERO NO ES PRIMO.");
}
      
    }//GEN-LAST:event_btnPrimo2ActionPerformed

    private void btnEN1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEN1ActionPerformed
        // TODO add your handling code here:
    int num = Integer.parseInt(txtNumero.getText());
    int sumatoria = 0;
       if(num<100){
    boolean prime = true; 
    for(int i = 2; i < num; i++) {
        sumatoria += i;
        if (num % i == 0) {
            prime = false;
            break;
        }
    }
    if (prime)
        lblMen.setText("EL NUMERO ES PRIMO.");
    else
        lblMen.setText("EL NUMERO NO ES PRIMO.");
}  
       lblMensaje.setText("LA SUMATORIA DE " +num+ " ES: " +sumatoria);
    }//GEN-LAST:event_btnEN1ActionPerformed

    private void btnRaizActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRaizActionPerformed
        // TODO add your handling code here:
        int num = Integer.parseInt(txtNumero.getText());
        double raizCuadrada = Math.sqrt(num);
    int sumatoria = 0;
       if(num<100){
    boolean prime = true; 
            double n = 0;
    for(int i = 2; i <= Math.sqrt(n); i++){
           if (n % i == 0) {
            prime = false;
            break;
        }
    }
    if (prime)
        lblMen.setText("EL NUMERO ES PRIMO.");
    else
        lblMen.setText("EL NUMERO NO ES PRIMO.");
}  
       lblMensaje.setText("LA RAIZ CUADRADA DE " +num+ " ES: " +raizCuadrada);
       }

{
       
        
    }//GEN-LAST:event_btnRaizActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ComprobacionNumerica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ComprobacionNumerica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ComprobacionNumerica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ComprobacionNumerica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ComprobacionNumerica().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnComprobar;
    private javax.swing.JButton btnEN1;
    private javax.swing.JButton btnPrimo;
    private javax.swing.JButton btnPrimo2;
    private javax.swing.JButton btnRaiz;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblMen;
    private javax.swing.JLabel lblMensaje;
    private javax.swing.JLabel lblNum;
    private javax.swing.JTextField txtNumero;
    // End of variables declaration//GEN-END:variables
}
